w <- read.table("data/agaricus-lepiota1.txt", header=T)
library(adabag)
set.seed(4410)
a <- boosting(V1 ~ ., w)
z0 <- table(w[, 1], predict(a, w)$class)
(E0 <- (sum(z0) - sum(diag(z0))) / sum(z0))
barplot(a$importance)

w <- read.table("data/housing.txt", header=T)
library(mboost)
set.seed(44)
b <- blackboost(MEDV ~ ., data=w)
y0 <- predict(b, w)
(NMSE0 <- mean((w$MEDV - y0)^2) / mean((w$MEDV - mean(w$MEDV))^2))
