w <- read.table("data/Dermatology1.txt", header=T)
w[, 35] <- factor(w[, 35])
library(e1071)
a <- svm(V35 ~ ., data=w, kernel="sigmoid")
z0 <- table(w[,35], predict(a, w))
(E0 <- (sum(z0) - sum(diag(z0))) / sum(z0))

w <- read.table("data/housing.txt", header=T)
w$CHAS <- factor(w$CHAS)
library(rminer)
set.seed(444)
M <- fit(MEDV ~ ., w, model="svm")
y0 <- predict(M, w)
(NMSE <- mean((w$MEDV - y0)^2) / mean((w$MEDV - mean(w$MEDV))^2))
